### PR TITLE
Use CryptoKit

### PR DESCRIPTION
**Pull request by ericlewis**
Use the new [Apple CryptoKit](https://developer.apple.com/documentation/cryptokit) under the hood when running iOS/iPadOS 13, macOS 10.15, or watchOS 6.0.

### CODE REVIEW

**Comment by ericlewis** [comment]
one of the tests failing here doesn't really seem like it should be, seems like wonky CI.

**Comment by mattrubin** [comment]
From the error code, it looks like one of Travis CI's typical inexplicable xcodebuild failures. I've restarted that CI job, which usually works for a flaky build.

Thanks for the PR! It's a busy week, but I'll try to review and merge it soon.

**Comment by ericlewis** [comment]
@mattrubin no problemo, I have a few more ambitious things to accomplish.

**Comment by ericlewis** [comment]
I am interested in moving towards a more protocol oriented composition and pulling a few things out, like legacy support (for now) & the token persistence mechanisms. I think with a protocol approach, it will be easier for folks to roll their own persisters. Such as secured CoreData stores and the like.

**Comment by ericlewis** [comment]
would also like to use your work on bases, modernize with a swift package, etc. so I might just use this as a reference.

**Comment by mattrubin** [comment]
While you're certainly welcome to use this project as a basis for your own implementation, most of the changes you mentioned (moving to Bases for base32 decoding, adding SPM support, pulling out the keychain integration and supporting alternative persistence stores) are on my roadmap for OneTimePassword. I can't promise any delivery dates for those features since I work on this project in my scarce free time, but PRs are always welcome!

I'm curious what your vision is for "protocol oriented composition". Just swappable persistence methods, or something more?

**Comment by ericlewis** [comment]
This is my vision: https://github.com/ericlewis/THOTP

Heavily inspired, but the Generators & Passwords are protocol based. This means we can switch out the actual implementation. So we could create a concrete type (NSManagedObject for instance) that conforms to PasswordProtocol and now we can use CoreData to persist a password since all of the functional generation implementation lives as protocols / extensions. You could do similarly for a keychain persistence layer as well. The more composable it is, the more powerful :)

I intend to release another framework that is a persistent layer, but it’s actually achievable super simply: using valet and a clever extension, plus some serialization code, and I had persistence parity in around 20 lines of code or so. On top of that, I conform to Identifiable, to make it easier to persist (since it’ll have an ID) as well as display in SwiftUI applications. 

My framework is not exactly the same as yours, I have no real desire for backwards compatibility currently. It wouldn’t really be too difficult to add it, tho. But for me it was easier to start from scratch, plus use all modern features directly.

**Comment by mattrubin** [comment]
@ericlewis Thanks for sharing this! It's interesting to see a different approach to the same functionality. I think the struct-based approach OneTimePassword takes is a better fit for my use case, but I may look more closely at using the protocol-oriented approach to make persistence extensible.

**Pull request merged**
