### PR TITLE
add SPM support

### PR DESCRIPTION
**Pull request by mrgrauel**
* adds Swift Package Manager support with `SwiftBase32` as dependency
* change `Base32` dependency to `SwiftBase32` for Carthage and Cocoapods
* rewrites legacy tests in swift
* increased iOS deployment target to iOS 10.3.1 and watchOS 3.2
* updates `travis.yml` to build with various Xcode versions (10 to 12)

### CODE REVIEW

**Comment by mrgrauel** [comment]
@mattrubin what is the purpose of the legacy tests? Has it a reason that `URL+Token.swift` isn't fully covered by `TokenSerializationTests.swift`?

**Comment by mrgrauel** [comment]
@mattrubin what do you think?

**Comment by mrgrauel** [comment]
@mattrubin do you know why travis-ci doesn’t report the status? The status works fine in my fork see https://github.com/mrgrauel/OneTimePassword/runs/1622053397

I cannot see any details of your Travis-CI. So I cannot fix it.

**Review by JCK-cloudLV — APPROVED** [review]

**Comment by mattrubin** [comment]
@mrgrauel Travis checks aren't running because Travis has severely limited their OSS offering. I migrated the project off of the deprecated Travis stack to their new stack, but now I'm stuck emailing Travis support periodically because that's the only way to get a refresh on the quickly-depleted OSS credits. Most of the CI jobs have been migrated to GitHub Actions, but Travis still remains the only way I know of to test on some of the older OS runtimes OneTimePassword still supports.

**Comment by mattrubin** [comment]
Thank you for this pull request! I recently merged https://github.com/mattrubin/OneTimePassword/pull/221, which adds SPM support using the current Base32 dependency, so I'm going to close this PR.

There's changes in your PR beyond SPM support that I'd still love to make – migrating the project to `SwiftBase32` and converting the legacy tests to Swift. If you're interested in splitting them out into their own PRs, I'd be happy to merge them!

**Pull request closed without merging**
