### PR TITLE
Make CommonCrypto dependency work for both Swift <4.2 and Swift 4.2 (CommonCrypto is public)

### PR DESCRIPTION
**Pull request by ziogaschr**
In Swift 4.2 and Xcode 10.0 the CommonCrypto framework became publicly available in iOS. For this reason, we had to remove the modulemap. For doing this, while keeping backward compatibility with later versions, we used an elegant method from @radianttap, who used a Build phase to check for CommonCrypto existence.

p.s.: Thanks @radianttap. I hope you are fine that I used your elegant handler.

### CODE REVIEW

**Comment by mattrubin** [comment]
Thanks for the PR, @ziogaschr! The changes [were failing to build on Xcode 9.x](https://travis-ci.org/mattrubin/OneTimePassword/builds/429922208), so I made [a small change](
https://github.com/mattrubin/OneTimePassword/pull/190/commits/47cacacc5b77a920694f4fa01bfcbbacac6babae) and pushed it to your branch to get the CI builds passing.

I like this new method of generating a modulemap at compile time only if necessary, rather than maintaining and linking external modulemap files. Before merging this PR, I'm going to test this new approach with Carthage and CocoaPods to make sure it works for all use cases.

**Comment by ziogaschr** [comment]
Oh nice catch @mattrubin, I tried to see if the patch works in another 3rd party lib and it worked nicely in Xcode 9, so I thought of just copy it here without testing it below Xcode10. Nice lesson for me, to not trust any code, likely Travis catch it.

**Comment by mattrubin** [comment]
I was never quite able to get this new approach working when building with CocoaPods, and now I've just [updated the whole project to build with Xcode 10](https://github.com/mattrubin/OneTimePassword/pull/201), removing the need for the modulemap shims. Thank you to @ziogaschr for the PR!

**Comment by ziogaschr** [comment]
I am glad there is a better way of doing this @mattrubin. Thx for maintaining this lib.

**Pull request closed without merging**
